// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ptos/c_buy_item.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {


}  // namespace


void protobuf_AssignDesc_ptos_2fc_5fbuy_5fitem_2eproto() {
  protobuf_AddDesc_ptos_2fc_5fbuy_5fitem_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ptos/c_buy_item.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ptos_2fc_5fbuy_5fitem_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_ptos_2fc_5fbuy_5fitem_2eproto() {
}

void protobuf_AddDesc_ptos_2fc_5fbuy_5fitem_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025ptos/c_buy_item.proto", 23);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ptos/c_buy_item.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ptos_2fc_5fbuy_5fitem_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ptos_2fc_5fbuy_5fitem_2eproto {
  StaticDescriptorInitializer_ptos_2fc_5fbuy_5fitem_2eproto() {
    protobuf_AddDesc_ptos_2fc_5fbuy_5fitem_2eproto();
  }
} static_descriptor_initializer_ptos_2fc_5fbuy_5fitem_2eproto_;


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
